dist: trusty
sudo: required
language: ruby
rvm:
- 2.3.1
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y -qq ruby-full pdftk xclip poppler-utils language-pack-pt libreoffice
- wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb && sudo dpkg -i pandoc-*.deb
- wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz && tar -xf install-tl-unx.tar.gz && cd install-tl-* && sudo ./install-tl -no-gui -profile ../spec/dependencias/texlive-abntex2.profile -no-verify-downloads && cd ..
- export PATH=$PATH:/usr/local/texlive/2018/bin/x86_64-linux

script:
- latexmk -v
- xelatex -v
- pdftotext -v
- pandoc -v
- libreoffice --version
- bundle exec rake
- bundle exec rake spec:latex
after_failure:
- cd /usr/local/texlive && find . -iname latexmk
- cat /usr/local/texlive/2017/install-tl.log
